-- MySQL Script generated by MySQL Workbench
-- Wed Oct 28 06:46:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workaccountaccount_idbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
CREATE DATABASE IF NOT EXISTS `mydb`;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` TINYINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `date_of_birth` DATETIME NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `phone_number` VARCHAR(11) NULL,
  `art_category` VARCHAR(10) NOT NULL,
  `art_category_tag` VARCHAR(10) NULL,
  `skill_lvl` CHAR(1) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_id` TINYINT NOT NULL AUTO_INCREMENT,
  `street_number` INT NULL,
  `street` VARCHAR(128) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `zipcode` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_Add`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_Add` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_Add` (
  `user` TINYINT NULL,
  `address` TINYINT NULL,
  INDEX `user_add__user_FK_idx` (`user` ASC),
  INDEX `user_add__address_FK_idx` (`address` ASC),
  CONSTRAINT `user_add__user_FK`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_add__address_FK`
    FOREIGN KEY (`address`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `account_id` TINYINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `acc_created` DATETIME NULL,
--  `activate` INT acc_createdactivate NOT NULL DEFAULT 0,
  `user` TINYINT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `account_user_FK_idx` (`user` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `account_user_FK`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`accountType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`accountType` (
  `account_type_id` TINYINT NOT NULL AUTO_INCREMENT,
  `account_type_desc` VARCHAR(45) NOT NULL,
  `account` TINYINT NOT NULL,
  PRIMARY KEY (`account_type_id`),
  INDEX `accountType_account_FK_idx` (`account` ASC),
  CONSTRAINT `accountType_account_FK`
    FOREIGN KEY (`account`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE CASCADE 
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`matches` ;

CREATE TABLE IF NOT EXISTS `mydb`.`matches` (
  `matches_id` TINYINT NOT NULL AUTO_INCREMENT,
  `client_username` VARCHAR(64) NOT NULL,
  `client_match_status` VARCHAR(10) NULL,
  PRIMARY KEY (`matches_id`),
  UNIQUE INDEX `client_username_UNIQUE` (`client_username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`preferences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`preferences` ;

CREATE TABLE IF NOT EXISTS `mydb`.`preferences` (
  `preferences_id` TINYINT NOT NULL AUTO_INCREMENT,
  `min_age` CHAR(2) NULL,
  `max_age` CHAR(2) NULL,
  `min_location` CHAR(3) NULL,
  `max_location` CHAR(3) NULL,
  `gender` CHAR(1) NULL,
  `art_preference` VARCHAR(10) NULL,
  `skill_lvl_pref` CHAR(1) NULL,
  `meeting_pref` VARCHAR(10) NULL,
  `user` TINYINT NOT NULL,
  `matches` TINYINT NULL,
  PRIMARY KEY (`preferences_id`),
  INDEX `preferences_user_FK_idx` (`user` ASC),
  INDEX `preferences_matches_FK_idx` (`matches` ASC),
  CONSTRAINT `preferences_user_FK`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `preferences_matches_FK`
    FOREIGN KEY (`matches`)
    REFERENCES `mydb`.`matches` (`matches_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filePath`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`file_Path` ;

CREATE TABLE IF NOT EXISTS `mydb`.`file_Path` (
  `file_path_id` TINYINT NOT NULL AUTO_INCREMENT,
  `profile_pic` VARCHAR(128) NULL,
  `picture_path` VARCHAR(128) NULL,
  `picture_desc` VARCHAR(255) NULL,
  `video_path` VARCHAR(128) NULL,
  `video_desc` VARCHAR(255) NULL,
  `audio_path` VARCHAR(128) NULL,
  `audio_descp` VARCHAR(255) NULL,
  `social_profile_1` VARCHAR(128) NULL,
  `social_profile_2` VARCHAR(128) NULL,
  `social_profile_3` VARCHAR(128) NULL,
  `social_profile_4` VARCHAR(128) NULL,
  `bio` VARCHAR(255) NULL,
  `user` TINYINT NULL,
  PRIMARY KEY (`file_path_id`),
  INDEX `file_path_user_FK_idx` (`user` ASC),
  CONSTRAINT `file_path_user_FK`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chat_file` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chat_file` (
  `chat_file_id` TINYINT NOT NULL AUTO_INCREMENT,
  `chat_file_name` INT NOT NULL,
  `chat_file_path` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`chat_file_id`),
  UNIQUE INDEX `chat_file_name_UNIQUE` (`chat_file_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chat_message` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chat_message` (
  `chat_message_id` TINYINT NOT NULL AUTO_INCREMENT,
  `user_id` TINYINT NOT NULL,
  `client_username` VARCHAR(64) NOT NULL,
  `msg_creation` DATETIME NOT NULL,
  `chat_file` TINYINT NOT NULL,
  PRIMARY KEY (`chat_message_id`),
  INDEX `caht_message_chat_file_FK_idx` (`chat_file` ASC),
  CONSTRAINT `caht_message_chat_file_FK`
    FOREIGN KEY (`chat_file`)
    REFERENCES `mydb`.`chat_file` (`chat_file_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chat` (
  `chat_id` TINYINT NOT NULL AUTO_INCREMENT,
  `matches` TINYINT NOT NULL,
  `chat_message` TINYINT NULL,
  PRIMARY KEY (`chat_id`),
  INDEX `chat_matches_FK_idx` (`matches` ASC),
  INDEX `chat__chat_message_FK_idx` (`chat_message` ASC),
  CONSTRAINT `chat_matches_FK`
    FOREIGN KEY (`matches`)
    REFERENCES `mydb`.`matches` (`matches_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `chat__chat_message_FK`
    FOREIGN KEY (`chat_message`)
    REFERENCES `mydb`.`chat_message` (`chat_message_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`communityPage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`communityPage` ;

CREATE TABLE IF NOT EXISTS `mydb`.`communityPage` (
  `comm_pg_id` TINYINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(64)  NULL,
  `last_name` VARCHAR(64) NULL,
  `post_title` VARCHAR(64) NOT NULL,
  `post_category` VARCHAR(15) NOT NULL,
  `post_description` VARCHAR(256) NULL,
  `post_file` VARCHAR(128) NULL,
  `post_votes` INT NULL,
  `post_creation` DATETIME NULL,
  `user` TINYINT NULL,
  PRIMARY KEY (`comm_pg_id`),
  INDEX `communityPage_user_FK_idx` (`user` ASC),
  CONSTRAINT `communityPage_user_FK`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`matches2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`matches2` ;

CREATE TABLE IF NOT EXISTS `mydb`.`matches2` (
  `user1` int NOT NULL,
  `match_status` int NOT NULL,
  `user2` int NOT NULL,
	UNIQUE `unique_index`(`user1`, `user2`))
ENGINE = InnoDB;

INSERT INTO `matches2` (`user1`, `match_status`, `user2`) VALUES (0, 0, 0);

INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (1, 'first', 'last',     'f','2000-11-21',    'mail@mail',        '7073334444',   'D',    'I');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (2, 'Bob',   'Smith',    'M','2000-12-12',    'Bobh@mail.com',    '7071112222',   'D',    'B');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (3, 'Bobba', 'Smith',    'F','2000-10-22',    'Bobba@mail.com',   '7071112223',   'D',    'E');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (4, 'Bin',   'Smith',    'F','2000-09-15',    'Bin@mail.com',     '7071112224',   'A',    'B');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (5, 'So',    'Smith',    'F','2000-08-13',    'So@mail.com',      '7071112225',   'M',    'B');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (6, 'Bobert','Smith',    'M','2000-07-16',    'Bobert@mail.com',  '7071112226',   'P',    'B');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (7, 'AHHHHH','Smith',    'M','2000-03-11',    'what@mail.com',    '7071112226',   'P',    'B');
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Alan',		'Holhs',	'1995-01-01',	'M',	'alan.holhs@gmail.com',		'Music',	'I',9877891234);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('John',		'Adams',	'2001-01-01',	'M',	'johnadams_22@gmail.com',	'Art',		'B',4231231234);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Jack',		'Gomez',	'1990-01-01',	'M',	'jack_g@yahoo.com',			'Dance',	'I',8980980865);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Jill',		'Rhodes',	'1992-01-01',	'F',	'jill_rho@mail.com',		'Dance',	'I',4345324412);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Mary',		'Beth',		'1987-01-01',	'F',	'mary_beth@gmail.com',		'Photo',	'E',4545436223);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Anne',		'Sullivan',	'1994-01-01',	'F',	'anne.sull12@gmail.com',	'Music',	'B',8878665576);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Jesus',		'Chavez',	'1989-01-01',	'M',	'j_chavez@yahoo.com',		'Film',		'E',6756744666);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Sabrina',	'Umbay',	'1991-01-01',	'F',	'sabrina.umbay@mail.com',	'Film',		'B',5654545444);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Bill',		'Lenox',	'1993-01-01',	'M',	'bill.lenox@yahoo.com',		'Music',	'I',7987568456);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Nick',		'Calum',	'1998-01-01',	'M',	'nickcalum98@yahoo.com',	'Music',	'E',4758475455);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Maddy',		'Jackson',	'2000-01-01',	'F',	'maddy_jack@gmail.com',		'Dance',	'B',3454356543);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Alex',		'Singh',	'2002-01-01',	'M',	'alex_singh24@yahoo.com',	'Art',		'I',4234325535);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Peter',		'Nye',		'1985-01-01',	'M',	'peter.n@gmail.com',		'Photo',	'B',5435576656);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Maya',		'Gomez',	'1993-01-01',	'F',	'maya.gomez@yahoo.com',		'Film',		'E',7543764756);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('David',		'Goliath',	'1990-01-01',	'M',	'david.gol@hotmail.com',	'Art',		'B',3432453346);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Mario',		'Flores',	'1991-01-01',	'F',	'mario.g.flores@gmail.com',	'Music',	'E',5678945675);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Lucy',		'Bell',		'1996-01-01',	'F',	'lucy_bell12@gmail.com',	'Music',	'I',5656500546);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Brad',		'Lint',		'2001-01-01',	'M',	'brand.lint@mail.com',	'	Dance',		'B',5468980990);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Felix',		'Johnson',	'2002-01-01',	'M',	'felix_jnson@yahoo.com',	'Film',		'E',4385406954);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Tom',		'Ford',		'1991-01-01',	'M',	'tom_ford415@gmail.com',	'Photo',	'B',5465787687);
INSERT INTO `mydb`.`user`(`first_name`,`last_name`,`date_of_birth`,`gender`,`email`,`art_category`,`skill_lvl`,`phone_number`) VALUES ('Frankie',	'Dane',		'1996-01-01',	'F',	'frankie.dane@mail.com',	'Art',		'I',6576588885);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('123', '123',    1);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('234', '234',    2);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('235', '235',    3);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('236', '236',    4);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('237', '237',    5);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('238', '238',    6);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('239', '239',    7);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('alanh','abc123',8);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('johna','1234er',9);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('jGomz','cfnm23',10);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('jrhod','jcje844',11);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('mary','jfbh458',12);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('annes','bfv324',13);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('jchavz','4358uj',14);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('sabby','t95086t',15);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('bill.l','jihgvm8',16);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('nick','hguirc',17);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('maddy','gcmtr',18);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('alex.s','mymtm',19);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('pete','ervgrg',20);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('maya','345452',21);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('david','fcjvc.r',22);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('mario','fcnn48',23);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('lucs','xwer35',24);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('brad','nuyu8',25);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('felix','rnxfgu',26);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('tommy','4354c',27);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('frankie','hfuhe7',28);
INSERT INTO `mydb`.`file_Path`(`user`,`picture_path`,`profile_pic`,`bio`) VALUES (1,    "/assets/users/1/",   'blobbored.png',    "This is test user 1 s bio (First Last)");
INSERT INTO `mydb`.`file_Path`(`user`,`picture_path`,`profile_pic`,`bio`) VALUES (2,    "/assets/users/2/",   'blobconfused.png', "bbbbbbbbbbbbbbb bob's bio (Bob Smith)");
INSERT INTO `mydb`.`file_Path`(`user`,`picture_path`,`profile_pic`,`bio`) VALUES (3,    "/assets/users/3/",   'test.png',         "aaaaaaaaaaaaaaaaaaaaa");
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (4);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (5);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (6);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (7);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (8);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (9);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (10);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (11);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (12);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (13);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (14);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (15);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (16);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (17);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (18);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (19);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (20);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (21);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (22);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (23);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (24);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (25);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (26);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (27);
INSERT INTO `mydb`.`file_Path`(`user`) VALUES (28);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(1);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(2);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(3);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(4);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(5);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(6);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(7);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(8);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(9);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(10);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(11);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(12);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(13);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(14);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(15);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(16);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(17);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(18);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(19);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(20);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(21);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(22);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(23);

INSERT INTO `mydb`.`communityPage`(`post_title`,`post_category`,`post_description`,`post_file`,`post_votes`,`user`) VALUES ('Test',   'Music', 'I am first',    'b.png',    3, 1);
INSERT INTO communityPage (`post_title`, `post_category`, `post_file`, `post_votes`, `user`) VALUES ('Egg Wobble','Art','egg.gif',25,'1');
INSERT INTO communityPage (`post_title`, `post_category`, `post_file`, `post_votes`, `user`) VALUES ('Avocado Blob','Art','477709683319373824.gif',22,'1');
UPDATE file_path SET `video_path` = 'Untitled.png' WHERE `user` = '1';
UPDATE file_path SET `video_desc` = 'test.jpg' WHERE `user` = '1';




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
