INSERT INTO `matches2` (`user1`, `match_status`, `user2`) VALUES (0, 0, 0);
INSERT INTO `mydb`.`communityPage`(`post_title`,`post_category`,`post_file`,`post_votes`) VALUES ('Test',   'Music',    'b.png',    1);
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (1, 'first', 'last',     'f','2000-11-21',    'mail@mail',        '7073334444',   'D',    'I');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (2, 'Bob',   'Smith',    'M','2000-12-12',    'Bobh@mail.com',    '7071112222',   'D',    'B');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (3, 'Bobba', 'Smith',    'F','2000-10-22',    'Bobba@mail.com',   '7071112223',   'D',    'E');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (4, 'Bin',   'Smith',    'F','2000-09-15',    'Bin@mail.com',     '7071112224',   'A',    'B');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (5, 'So',    'Smith',    'F','2000-08-13',    'So@mail.com',      '7071112225',   'M',    'B');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (6, 'Bobert','Smith',    'M','2000-07-16',    'Bobert@mail.com',  '7071112226',   'P',    'B');
INSERT INTO `mydb`.`user`(`user_id`, `first_name`,`last_name`,`gender`,`date_of_birth`,`email`,`phone_number`,`art_category`,`skill_lvl`) VALUES (7, 'AHHHHH','Smith',    'M','2000-03-11',    'what@mail.com',    '7071112226',   'P',    'B');
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('123', '123',    1);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('234', '234',    2);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('235', '235',    3);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('236', '236',    4);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('237', '237',    5);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('238', '238',    6);
INSERT INTO `mydb`.`account`(`username`,`password`,`user`) VALUES ('239', '239',    7);
INSERT INTO `mydb`.`file_Path`(`user`,`picture_path`,`profile_pic`,`bio`) VALUES (1,    "/assets/users/1/",   'blobbored.png',    "This is test user 1 s bio (First Last)");
INSERT INTO `mydb`.`file_Path`(`user`,`picture_path`,`profile_pic`,`bio`) VALUES (2,    "/assets/users/2/",   'blobconfused.png', "bbbbbbbbbbbbbbb bob's bio (First Last)");
INSERT INTO `mydb`.`file_Path`(`user`,`picture_path`,`profile_pic`,`bio`) VALUES (3,    "/assets/users/3/",   'test.png',         "aaaaaaaaaaaaaaaaaaaaa");
INSERT INTO `mydb`.`preferences`(`user`) VALUES(1);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(2);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(3);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(4);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(5);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(6);
INSERT INTO `mydb`.`preferences`(`user`) VALUES(7);
